### ISSUE TITLE
Attempting to carry protected (trader) crate crash

### ISSUE THREAD

**Issue by lordebon** [copygirl/CarryCapacity#5] opened 2020-04-04 19:13 UTC
Hi copygirl,

The below crash happened when attempting to pick up a wooden crate that belonged to a trader (was curious what would happen :D) - was able to carry one fine in a test world that didnt have the claim.

```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.12.11 (Stable)4/4/2020 3:07:06 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.SystemRenderPlayerEffects.onBeforeRender(Single dt)
   at _ZWyx8V7GBY20FZhd02o5wlkBhTM._3MzjqAt5GiJmvnVzhdiANDAEMCB(EnumRenderStage , Single )
   at _12aioOzLogzcJMHhplAX1ctUKPP._3MzjqAt5GiJmvnVzhdiANDAEMCB(EnumRenderStage , Single )
   at _12aioOzLogzcJMHhplAX1ctUKPP._EwXRd5TjiEjwEnwkgR6SD2VwKOi(Single )
   at _12aioOzLogzcJMHhplAX1ctUKPP._H2qn3yZXJ5qaROCXlgxZgsHhHqt(Single )
   at _N5xEhV0YMy0mMOwBe09dKlcWjwu._DmGyRRAceBU1Y01pLfQvCPqzM3A(Single )
   at _TjqHBJw2IYSAlyXCQYRZyDjXkjs._f3BqvaJbeJjUlO1Vz6UZg7yIMVf(Single )
   at _TjqHBJw2IYSAlyXCQYRZyDjXkjs._cEEYga8RkvUZyLxVZDIQqvmAaRE(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _KhgOJjJMqvBmMftdPC9NuNGCr2l._KJdbFdyRyPI3RBGfknJMDw7qv3g(_z0CXJGPbPfszOCyrvlmbpR4Uq8q , String[] )
   at _W7oHr1XmopiBCmRiVK2Gh8gGNEX._KJdbFdyRyPI3RBGfknJMDw7qv3g(ThreadStart )
-------------------------------
```

**Comment by copygirl** [comment] 2020-04-05 06:55
This is really strange, because the crash occurs completely in Vanilla game code, in a method that doesn't appear to run any code related to CarryCapacity. I've also thoroughly tested claims and never ran into that issue. Can you reproduce it yourself?

**Comment by lordebon** [comment] 2020-04-05 11:06
Yes, I confirmed I was able to repro it. Just tested again and was able to get another crash in a new SP world when trying to carry a crate in a trader. It looks like its specific to the crate though - when I try to carry a basket I get the expected behavior (it says its claimed and goes back).

Got a bit different trace with this crash in SP - see below.

```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.12.11 (Stable)4/5/2020 7:03:59 AM: Critical error occurred
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.ReadString()
   at Vintagestory.API.Datastructures.TreeAttribute.FromBytes(BinaryReader stream)
   at Vintagestory.API.Datastructures.SyncedTreeAttribute.PartialUpdate(String path, Byte[] data)
   at Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntityAttributeUpdatePacket(_3NBAkeZDOgoENpKgL4vAaXffuUXA p)
   at Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntityBulkAttributesPacket(_FWsbf8vJdTSNh7GxC1oaO3PfUtN packet)
   at _12aioOzLogzcJMHhplAX1ctUKPP._gZJf2GOkTz39Q4AUiGcV6ZznQpc(Single )
   at _N5xEhV0YMy0mMOwBe09dKlcWjwu._DmGyRRAceBU1Y01pLfQvCPqzM3A(Single )
   at _TjqHBJw2IYSAlyXCQYRZyDjXkjs._f3BqvaJbeJjUlO1Vz6UZg7yIMVf(Single )
   at _TjqHBJw2IYSAlyXCQYRZyDjXkjs._cEEYga8RkvUZyLxVZDIQqvmAaRE(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _KhgOJjJMqvBmMftdPC9NuNGCr2l._KJdbFdyRyPI3RBGfknJMDw7qv3g(_z0CXJGPbPfszOCyrvlmbpR4Uq8q , String[] )
   at _W7oHr1XmopiBCmRiVK2Gh8gGNEX._KJdbFdyRyPI3RBGfknJMDw7qv3g(ThreadStart )
-------------------------------

```

**Comment by copygirl** [comment] 2022-02-14 18:14
No idea if this is still happening. Might have been fixed in the game.

**Closed as completed by copygirl** 2022-02-14 18:14 UTC
Labels: bug
