### ISSUE TITLE
Attacking traders and trying to steal.

### ISSUE THREAD

**Issue by murd3rh0b0** [copygirl/CarryCapacity#8] opened 2020-10-07 18:21 UTC
Threw a flint spear at a trader causing game crash. Very easy to repeat.

CarryCapacity-0.4.10

Version: v1.13.4 (Stable)10/7/2020 10:57:49 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.ItemSpear.OnHeldInteractStop(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _VtIDI6oYFpyEcQSZBFso9UVxS9aA._ZnYzeuHqveMMiEvOnpahncAMjfg(Single )
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._4BykKOCicJqCBHpyWIgTmxWrTrg(Single )
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._6XmOxKoTYrFLRCGd58p58XW43nD(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._EEzpApWBQHtHR4iMJabXK2wDvlA(_ex0VSgRAdtsvhANmJHZHaf9ATWt , String[] )
   at _IcGByoJhapvESnm6vaOawAHbkeU._EEzpApWBQHtHR4iMJabXK2wDvlA(ThreadStart )

**Comment by copygirl** [comment] 2020-10-07 18:29
Does this not happen without CarryCapacity? I feel like I remember there have been issues reported with spears but they couldn't be reproduced by the developers. edit: Additionally, the second crash has been reported before: #5

**Comment by murd3rh0b0** [comment] 2020-10-07 18:33
No, it works just fine without CarryCapacity, but the moment it's back in it instantly causes a crash every time. I took all mods off after replicating the first time to make sure it wasn't vanilla, and it doesn't seem to happen with any other mods active. Yeah, I noticed after looking around. I seem to have a bad habit of speaking before seeing if something has been said.

**Comment by murd3rh0b0** [comment] 2020-10-07 18:49
It seems more common when throwing from outside the door, rather then inside.

**Comment by copygirl** [comment] 2020-10-08 06:26
Oddly enough, I can't reproduce this in my moddev environment ... Typical.

**Comment by copygirl** [comment] 2022-02-14 18:16
I've not heard this happening any more, so I assume this has been fixed in the game.

**Closed as completed by copygirl** 2022-02-14 18:16 UTC
Labels: bug
